[package]
name = "libsw"
version = "0.1.0"
authors = ["Ula Shipman <ula.hello@mailbox.org>"]
edition = "2021"
description = "stopwatch library"
repository = "https://github.com/ulahello/libsw"
license = "MIT OR GPL-3.0-or-later"
keywords = ["stopwatch"]
