[package]
name = "libsw"
version = "2.0.1"
authors = ["Ula Shipman <ula.hello@mailbox.org>"]
edition = "2021"
rust-version = "1.58.1"
description = "Comprehensive stopwatch library"
documentation = "https://docs.rs/libsw"
homepage = "https://crates.io/crates/libsw"
repository = "https://github.com/ulahello/libsw"
license = "MIT OR Apache-2.0"
keywords = ["stopwatch"]
categories = ["date-and-time"]
